TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += main.proto

#=======================================
include $(TOP)/configure/RULES
