TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += $(TOP)/neoceraSup/devneocera.proto

#=======================================
include $(TOP)/configure/RULES
